# Generated by Django 5.0.7 on 2024-08-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('V', 'Validé'), ('A', 'En attente')], default='A', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, default='fallback.txt', upload_to='')),
                ('position', models.CharField(max_length=300)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.employee')),
            ],
        ),
    ]
