# Generated by Django 5.0.7 on 2024-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, default='fallback.txt', upload_to=''),
        ),
    ]
