# Generated by Django 5.0.7 on 2024-08-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comment',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='candidate',
            name='entity',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='candidate',
            name='oto_interview',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='sub_entity',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='candidate',
            name='teams_interview',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='candidate',
            name='technical_interview',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('V', 'Validé'), ('EA', 'En attente'), ('NR', 'Non retenu'), ('AB', 'Absent'), ('NG', 'Négotiation')], default='EA', max_length=2),
        ),
    ]
