# Generated by Django 5.0.7 on 2024-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='author',
        ),
    ]
